# Generated by Django 6.0.3 on 2026-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
